[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "base58>=2.1.1",
    "flask>=3.1.2",
    "psutil>=7.1.0",
    "requests>=2.32.5",
    "tronpy>=0.6.1",
]
